export { default as Navbar } from './navbar/Navbar';
export { default as About } from './about/About';
export { default as Projects } from './projects/Projects';
export { default as Contact } from './contact/Contact';
export { default as Wrapper } from './Wrapper';
export { default as CircularProgressBar } from './CircularProgressBar';
export { default as PumbaProject } from './project_pages/Pumba_project';
export { default as Events } from './project_pages/Events';
export { default as NogaYoga } from './project_pages/Noga_yoga_app';